
# with Minitest::Unit
guard :minitest,
			test_folders: ['tests'],
			test_file_patterns: ["tc_*.rb"] do

	watch(%r{^lib/mqtt/([^/]+)\.rb}) { |m| "tests/tc_#{m[1]}.rb"}
	watch(%r{^tests/tc_(.*).rb})
end
